version: '3.3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

  user:
    build:
      context: ./user
    restart: always
    ports:
      - "10206:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

volumes:
  db:


networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
