name: CI/CD with Gradle and Heroku

on:
  push:
    branches:
      - inventaris

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: myjisc-inventaris

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew script
        run: |
          chmod +x inventaris/gradlew

      - name: Set up environment variables
        run: |
          export DATABASE_URL="$DATABASE_URL"
          export DATABASE_USERNAME="$DATABASE_USERNAME"
          export DATABASE_PASSWORD="$DATABASE_PASSWORD"
          echo "Database URL: $DATABASE_URL"

      - name: Build with Gradle
        run: |
          cd inventaris
          ./gradlew build --stacktrace --info

      - name: Deploy to Heroku
        run: |
          echo "Build successful, changes will be automatically deployed by Heroku"
