name: CI/CD with Gradle and Heroku

on:
  push:
    branches:
      - inventaris

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew script
        run: |
          chmod +x inventaris/gradlew

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> inventaris/.env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> inventaris/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> inventaris/.env

      - name: Build with Gradle
        run: |
          cd inventaris
          ./gradlew build

      - name: Deploy to Heroku
        run: |
          echo "Build successful, changes will be automatically deployed by Heroku"
